In [6]:
import numpy as np

In [12]:
a = np.zeros(5)
a
a.dtype

dtype('float64')

In [9]:
b = np.ones(5)
b


array([1., 1., 1., 1., 1.])

In [10]:
b.dtype

dtype('float64')

In [14]:
c = np.full(5,7)
c

array([7, 7, 7, 7, 7])

In [19]:
ar = np.arange(2,20,3)
ar

array([ 2,  5,  8, 11, 14, 17])

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
np.arange(20,2)

array([], dtype=int64)