In [4]:
import numpy as np
#RESHAPING INS NUMPY

In [4]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [8]:
a.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [14]:
a.reshape(3,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
a.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
a.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
a.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [17]:
#FLATTENING IN NUMPY 
b = np.array([
    [1,2,3],
    [4,5,6]
])

b

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
b.flatten()

array([1, 2, 3, 4, 5, 6])

In [20]:
b.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [21]:
#RANDOOM NUMBERS IN NUMPY
np.random.rand(5)

array([0.4101751 , 0.28473493, 0.24219012, 0.96277042, 0.09321527])

In [22]:
np.random.rand(5)

array([0.8560915 , 0.22183028, 0.21970254, 0.33678312, 0.21292889])

In [23]:
np.random.randint(1,10,5)

array([6, 7, 9, 9, 7], dtype=int32)

In [5]:
ar = np.random.seed(42)


In [7]:
#CHALLENGE
a = np.arange(1,17)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [8]:
a.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [9]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])