In [1]:
import numpy as np
#AGGREGATE FUNTIONS IN 1D ARRAY

In [2]:
a = np.array([10,20,30,40,50])

In [3]:
a.sum()

np.int64(150)

In [4]:
a.mean()

np.float64(30.0)

In [5]:
a.min()

np.int64(10)

In [8]:
a.max()

np.int64(50)

In [9]:
a.argmax() #WHERE THE LARGE NUMBER IS

np.int64(4)

In [10]:
a.argmin() #WHERE THE SMALLLEST NUMBER IS 

np.int64(0)

In [11]:
a.std()

np.float64(14.142135623730951)

In [12]:
a.var()

np.float64(200.0)

In [15]:
#AGGREGATE FUNTIONS IN 2D ARRAY
b = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90],
])
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
b.sum()

np.int64(450)

In [17]:
b.sum(axis=0)

array([120, 150, 180])

In [18]:
b.sum(axis=1)

array([ 60, 150, 240])

In [20]:
b.max(axis=1)

array([30, 60, 90])

In [22]:
#BOOLEAN INDEXING
m = np.array([23,56,78,34,56,76,73])
m

array([23, 56, 78, 34, 56, 76, 73])

In [24]:
print(m>35)

[False  True  True False  True  True  True]


In [25]:
m == 35

array([False, False, False, False, False, False, False])

In [26]:
m !=73

array([ True,  True,  True,  True,  True,  True, False])

In [27]:
m[m>35]

array([56, 78, 56, 76, 73])

In [28]:
m[(m > 50) & (m < 90)]

array([56, 78, 56, 76, 73])

In [29]:
marks = np.array([45,67,89,23,91])

In [30]:
marks[marks>80]

array([89, 91])

In [32]:
#BRODCASTING IN NUMPY
a = np.array([10,20,30,40])
a + 10

array([20, 30, 40, 50])

In [33]:
a

array([10, 20, 30, 40])

In [34]:
b = np.array([40,30,20,10])
a+b

array([50, 50, 50, 50])

In [35]:
a*b

array([400, 600, 600, 400])

In [36]:
#NOW IN 2D ELEMENTS
a = np.array([
    [1,2,3],
    [4,5,6]
])
a+10

array([[11, 12, 13],
       [14, 15, 16]])

In [37]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([10,20,30])

a+b

array([[11, 22, 33],
       [14, 25, 36]])

In [38]:
a = np.array([
    [1],
    [2]
])

b = np.array([10,20,30])

a+b

array([[11, 21, 31],
       [12, 22, 32]])

In [39]:
#MORE OF NUMPY
arr = np.array([1,2,2,3,4,4,5,5,5])

np.unique(arr)

array([1, 2, 3, 4, 5])

In [45]:
arr = np.array([8,3,1,6,2])

np.sort(arr)

array([1, 2, 3, 6, 8])

In [46]:
arr

array([8, 3, 1, 6, 2])

In [47]:
arr = np.array([1,2,3,4,5,6])

np.count_nonzero(arr)

np.int64(6)

In [48]:
arr = np.array([1,0,0,4,0,6])

np.count_nonzero(arr)

np.int64(3)

In [49]:
arr = np.array([10,20,30,40,50])

np.where(arr>25) #RETURNS INDEXES

(array([2, 3, 4]),)

In [51]:
arr[np.where(arr>25)] #RETURNS THE ACTUAL VALES

array([30, 40, 50])

In [52]:
arr = np.array([True,True,False])

np.any(arr)

np.True_

In [53]:
np.all(arr)

np.False_

In [54]:
arr = np.array([10,25,80,120])

np.clip(arr,20,100)

array([ 20,  25,  80, 100])