In [1]:
import numpy as np


In [2]:
marks = np.array([
    [85,78,92],
    [67,88,75],
    [95,91,89],
    [72,64,81]
])

In [5]:
marks.shape # 4 students and 3 subjects

(4, 3)

In [6]:
marks.size

12

In [9]:
highest_score = marks.max(axis=0)
highest_score #In maths and physics std2 got highest_score and in chemistry std1 got highest_score 

array([95, 91, 92])

In [10]:
low_score= marks.min(axis=0)
low_score

array([67, 64, 75])

In [11]:
avg_score = marks.mean(axis=0) #avg score in maths physics and chemistry
avg_score

array([79.75, 80.25, 84.25])

In [12]:
avgof_std = marks.mean(axis=1)
avgof_std

array([85.        , 76.66666667, 91.66666667, 72.33333333])

In [14]:
distintion = marks[marks>90]
distintion

array([92, 95, 91])

In [15]:
marks

array([[85, 78, 92],
       [67, 88, 75],
       [95, 91, 89],
       [72, 64, 81]])

In [16]:
marks+5

array([[ 90,  83,  97],
       [ 72,  93,  80],
       [100,  96,  94],
       [ 77,  69,  86]])

In [18]:
marks.flatten()

array([85, 78, 92, 67, 88, 75, 95, 91, 89, 72, 64, 81])

In [19]:
marks.reshape(2,6)

array([[85, 78, 92, 67, 88, 75],
       [95, 91, 89, 72, 64, 81]])